FROM node:15.10.0-alpine

RUN mkdir -p /usr/src/app && chown -R node:node /usr/src/app
WORKDIR /usr/src/app

ENV PATH ./node_modules/.bin:$PATH

COPY package.json .
RUN npm install

COPY . .

EXPOSE 4000
CMD ["npm", "start"]