FROM node

RUN mkdir -p /usr/src/api
WORKDIR /usr/src/api

COPY package.json .
RUN npm install

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

COPY . .

EXPOSE 3000
CMD /wait && npm run dev